---
- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev

- name: download nvm
  git: >
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    version={{ nvm.version }}

- name: Source nvm
  lineinfile: >
    dest={{ nvm.shell_source }}
    line={{ item }}
    create=yes
    state=present
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'

- name: check node version {{ nvm.node_version }}
  shell: . {{ nvm.shell_source }} && nvm use {{ nvm.node_version }}
  register: nvm_use_test
  changed_when: False
  ignore_errors: True

- name: Install {{ nvm.node_version }}
  shell: . {{ nvm.shell_source }} && nvm install {{ nvm.node_version }}
  when: "'N/A' in nvm_use_test.stderr"

- name: Check if {{ nvm.node_version }} is the default node version
  shell: . {{ nvm.shell_source }} && nvm ls | grep -e 'default -> {{ nvm.node_version }}'
  register: nvm_check_default
  changed_when: False
  ignore_errors: True

- name: Set default node version to {{ nvm.node_version }}
  shell: . {{ nvm.shell_source }} && nvm alias default {{ nvm.node_version }}
  when: nvm_check_default|failed
